// Code generated by gen_errors. DO NOT EDIT.

/*
 * error_codes_generated.go
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2013-2026 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fdb

// To regenerate this file from the bindings/go/src directory
// go run ../internal/gen_errors/main.go -in ../../../../flow/include/flow/error_definitions.h -out error_codes_generated.go
//
// Error sentinel variables derived from flow/include/flow/error_definitions.h.
// Use with errors.Is to match a specific FoundationDB error code:
//
//	errors.Is(err, fdb.ErrTransactionTooOld)
var (
	// Success
	ErrSuccess = Error{Code: 0}
	// End of stream
	ErrEndOfStream = Error{Code: 1}
	// Operation failed
	ErrOperationFailed = Error{Code: 1000}
	// Shard is not available from this server
	ErrWrongShardServer = Error{Code: 1001}
	// Operation result no longer necessary
	ErrOperationObsolete = Error{Code: 1002}
	// Cache server is not warm for this range
	ErrColdCacheServer = Error{Code: 1003}
	// Operation timed out
	ErrTimedOut = Error{Code: 1004}
	// Conflict occurred while changing coordination information
	ErrCoordinatedStateConflict = Error{Code: 1005}
	// All alternatives failed
	ErrAllAlternativesFailed = Error{Code: 1006}
	// Transaction is too old to perform reads or be committed
	ErrTransactionTooOld = Error{Code: 1007}
	// Not enough physical servers available
	ErrNoMoreServers = Error{Code: 1008}
	// Request for future version
	ErrFutureVersion = Error{Code: 1009}
	// Conflicting attempts to change data distribution
	ErrMovekeysConflict = Error{Code: 1010}
	// TLog stopped
	ErrTLogStopped = Error{Code: 1011}
	// Server request queue is full
	ErrServerRequestQueueFull = Error{Code: 1012}
	// Transaction not committed due to conflict with another transaction
	ErrNotCommitted = Error{Code: 1020}
	// Transaction may or may not have committed
	ErrCommitUnknownResult = Error{Code: 1021}
	// Idempotency id for transaction may have expired, so the commit status of the transaction cannot be determined
	ErrCommitUnknownResultFatal = Error{Code: 1022}
	// Operation aborted because the transaction was cancelled
	ErrTransactionCancelled = Error{Code: 1025}
	// Network connection failed
	ErrConnectionFailed = Error{Code: 1026}
	// Coordination servers have changed
	ErrCoordinatorsChanged = Error{Code: 1027}
	// New coordination servers did not respond in a timely way
	ErrNewCoordinatorsTimedOut = Error{Code: 1028}
	// Watch cancelled because storage server watch limit exceeded
	ErrWatchCancelled = Error{Code: 1029}
	// Request may or may not have been delivered
	ErrRequestMaybeDelivered = Error{Code: 1030}
	// Operation aborted because the transaction timed out
	ErrTransactionTimedOut = Error{Code: 1031}
	// Too many watches currently set
	ErrTooManyWatches = Error{Code: 1032}
	// Locality information not available
	ErrLocalityInformationUnavailable = Error{Code: 1033}
	// Watches cannot be set if read your writes is disabled
	ErrWatchesDisabled = Error{Code: 1034}
	// Default error for an ErrorOr object
	ErrDefaultErrorOr = Error{Code: 1035}
	// Read or wrote an unreadable key
	ErrAccessedUnreadable = Error{Code: 1036}
	// Storage process does not have recent mutations
	ErrProcessBehind = Error{Code: 1037}
	// Database is locked
	ErrDatabaseLocked = Error{Code: 1038}
	// The protocol version of the cluster has changed
	ErrClusterVersionChanged = Error{Code: 1039}
	// External client has already been loaded
	ErrExternalClientAlreadyLoaded = Error{Code: 1040}
	// DNS lookup failed
	ErrLookupFailed = Error{Code: 1041}
	// CommitProxy commit memory limit exceeded
	ErrCommitProxyMemoryLimitExceeded = Error{Code: 1042}
	// Operation no longer supported due to shutdown
	ErrShutdownInProgress = Error{Code: 1043}
	// Failed to deserialize an object
	ErrSerializationFailed = Error{Code: 1044}
	// No peer references for connection
	ErrConnectionUnreferenced = Error{Code: 1048}
	// Connection closed after idle timeout
	ErrConnectionIdle = Error{Code: 1049}
	// The disk queue adapter reset
	ErrDiskAdapterReset = Error{Code: 1050}
	// Batch GRV request rate limit exceeded
	ErrBatchTransactionThrottled = Error{Code: 1051}
	// Data distribution components cancelled
	ErrDdCancelled = Error{Code: 1052}
	// Data distributor not found
	ErrDdNotFound = Error{Code: 1053}
	// Connection file mismatch
	ErrWrongConnectionFile = Error{Code: 1054}
	// The requested changes have been compacted away
	ErrVersionAlreadyCompacted = Error{Code: 1055}
	// Local configuration file has changed. Restart and apply these changes
	ErrLocalConfigChanged = Error{Code: 1056}
	// Format version not supported
	ErrUnsupportedFormatVersion = Error{Code: 1058}
	// Change feed not found
	ErrUnknownChangeFeed = Error{Code: 1059}
	// Change feed not registered
	ErrChangeFeedNotRegistered = Error{Code: 1060}
	// Change feed was cancelled
	ErrChangeFeedCancelled = Error{Code: 1062}
	// Tried to read a version older than what has been popped from the change feed
	ErrChangeFeedPopped = Error{Code: 1066}
	// Page header does not match location on disk
	ErrPageHeaderWrongPageID = Error{Code: 1068}
	// Page header checksum failed
	ErrPageHeaderChecksumFailed = Error{Code: 1069}
	// Page header version is not supported
	ErrPageHeaderVersionNotSupported = Error{Code: 1070}
	// Page encoding type is not supported or not valid
	ErrPageEncodingNotSupported = Error{Code: 1071}
	// Page content decoding failed
	ErrPageDecodingFailed = Error{Code: 1072}
	// Page content decoding failed
	ErrUnexpectedEncodingType = Error{Code: 1073}
	// Encryption key not found
	ErrEncryptionKeyNotFound = Error{Code: 1074}
	// Data move was cancelled
	ErrDataMoveCancelled = Error{Code: 1075}
	// Dest team was not found for data move
	ErrDataMoveDestTeamNotFound = Error{Code: 1076}
	// GetReadVersion proxy memory limit exceeded
	ErrGRVProxyMemoryLimitExceeded = Error{Code: 1078}
	// Too many feed streams to a single storage server
	ErrStorageTooManyFeedStreams = Error{Code: 1080}
	// Storage engine was never successfully initialized.
	ErrStorageEngineNotInitialized = Error{Code: 1081}
	// Storage engine type is not recognized.
	ErrUnknownStorageEngine = Error{Code: 1082}
	// A duplicate snapshot request has been sent, the old request is discarded.
	ErrDuplicateSnapshotRequest = Error{Code: 1083}
	// DataDistribution configuration changed.
	ErrDdConfigChanged = Error{Code: 1084}
	// Consistency check urgent task is failed
	ErrConsistencyCheckUrgentTaskFailed = Error{Code: 1085}
	// Data move conflict in SS
	ErrDataMoveConflict = Error{Code: 1086}
	// Consistency check urgent got a duplicate request
	ErrConsistencyCheckUrgentDuplicateRequest = Error{Code: 1087}
	// Broken promise
	ErrBrokenPromise = Error{Code: 1100}
	// Asynchronous operation cancelled
	ErrOperationCancelled = Error{Code: 1101}
	// Future has been released
	ErrFutureReleased = Error{Code: 1102}
	// Connection object leaked
	ErrConnectionLeaked = Error{Code: 1103}
	// Never reply to the request
	ErrNeverReply = Error{Code: 1104}
	// Retry operation
	ErrRetry = Error{Code: 1105}
	// Recruitment of a server failed
	ErrRecruitmentFailed = Error{Code: 1200}
	// Attempt to move keys to a storage server that was removed
	ErrMoveToRemovedServer = Error{Code: 1201}
	// Normal worker shut down
	ErrWorkerRemoved = Error{Code: 1202}
	// Cluster recovery failed
	ErrClusterRecoveryFailed = Error{Code: 1203}
	// Master hit maximum number of versions in flight
	ErrMasterMaxVersionsInFlight = Error{Code: 1204}
	// Cluster recovery terminating because a TLog failed
	ErrTLogFailed = Error{Code: 1205}
	// Recovery of a worker process failed
	ErrWorkerRecoveryFailed = Error{Code: 1206}
	// Reboot of server process requested
	ErrPleaseReboot = Error{Code: 1207}
	// Reboot of server process requested, with deletion of state
	ErrPleaseRebootDelete = Error{Code: 1208}
	// Master terminating because a CommitProxy failed
	ErrCommitProxyFailed = Error{Code: 1209}
	// Cluster recovery terminating because a Resolver failed
	ErrResolverFailed = Error{Code: 1210}
	// Server is under too much load and cannot respond
	ErrServerOverloaded = Error{Code: 1211}
	// Cluster recovery terminating because a backup worker failed
	ErrBackupWorkerFailed = Error{Code: 1212}
	// Transaction tag is being throttled
	ErrTagThrottled = Error{Code: 1213}
	// Cluster recovery terminating because a GRVProxy failed
	ErrGRVProxyFailed = Error{Code: 1214}
	// The data distribution tracker has been cancelled
	ErrDdTrackerCancelled = Error{Code: 1215}
	// Process has failed to make sufficient progress
	ErrFailedToProgress = Error{Code: 1216}
	// Attempted to join cluster with a different cluster ID
	ErrInvalidClusterID = Error{Code: 1217}
	// Restart cluster controller process
	ErrRestartClusterController = Error{Code: 1218}
	// Need to reboot the storage engine
	ErrPleaseRebootKVStore = Error{Code: 1219}
	// Current software does not support database format
	ErrIncompatibleSoftwareVersion = Error{Code: 1220}
	// Validate storage consistency operation failed
	ErrAuditStorageFailed = Error{Code: 1221}
	// Exceeded the max number of allowed concurrent audit storage requests
	ErrAuditStorageExceededRequestLimit = Error{Code: 1222}
	// Exceeded maximum proxy tag throttling duration
	ErrProxyTagThrottled = Error{Code: 1223}
	// Exceeded maximum time allowed to read or write.
	ErrKeyValueStoreDeadlineExceeded = Error{Code: 1224}
	// Found data corruption
	ErrAuditStorageError = Error{Code: 1226}
	// Cluster recovery terminating because master has failed
	ErrMasterFailed = Error{Code: 1227}
	// Test failed
	ErrTestFailed = Error{Code: 1228}
	// Need background datamove cleanup
	ErrRetryCleanUpDatamoveTombstoneAdded = Error{Code: 1229}
	// Persist new audit metadata error
	ErrPersistNewAuditMetadataError = Error{Code: 1230}
	// Failed to cancel an audit
	ErrCancelAuditStorageFailed = Error{Code: 1231}
	// Audit has been cancelled
	ErrAuditStorageCancelled = Error{Code: 1232}
	// Found location metadata corruption
	ErrLocationMetadataCorruption = Error{Code: 1233}
	// Audit task is scheduled by an outdated DD
	ErrAuditStorageTaskOutdated = Error{Code: 1234}
	// Transaction throttled due to hot shard
	ErrTransactionThrottledHotShard = Error{Code: 1235}
	// Storage replicas not consistent
	ErrStorageReplicaComparisonError = Error{Code: 1236}
	// Storage replica cannot be reached
	ErrUnreachableStorageReplica = Error{Code: 1237}
	// Bulk loading task failed
	ErrBulkloadTaskFailed = Error{Code: 1238}
	// Bulk loading task outdated
	ErrBulkloadTaskOutdated = Error{Code: 1239}
	// Lock range failed
	ErrRangeLockFailed = Error{Code: 1241}
	// Transaction rejected due to range lock
	ErrTransactionRejectedRangeLocked = Error{Code: 1242}
	// Bulk dumping task failed
	ErrBulkdumpTaskFailed = Error{Code: 1243}
	// Bulk dumping task outdated
	ErrBulkdumpTaskOutdated = Error{Code: 1244}
	// Bulkload fileset provides invalid filepath
	ErrBulkloadFilesetInvalidFilepath = Error{Code: 1245}
	// Bulkload manifest string is failed to decode
	ErrBulkloadManifestDecodeError = Error{Code: 1246}
	// Range lock is rejected
	ErrRangeLockReject = Error{Code: 1247}
	// Range unlock is rejected
	ErrRangeUnlockReject = Error{Code: 1248}
	// Bulkload dataset does not cover the required range
	ErrBulkloadDatasetNotCoverRequiredRange = Error{Code: 1249}
	// BulkLoad requires cluster configuration with both shard_encode_location_metadata=1 and enable_read_lock_on_range=1
	ErrBulkloadInvalidConfiguration = Error{Code: 1250}
	// Platform error
	ErrPlatformError = Error{Code: 1500}
	// Large block allocation failed
	ErrLargeAllocFailed = Error{Code: 1501}
	// QueryPerformanceCounter error
	ErrPerformanceCounterError = Error{Code: 1502}
	// Null allocator was used to allocate memory
	ErrBadAllocator = Error{Code: 1503}
	// Disk i/o operation failed
	ErrIOError = Error{Code: 1510}
	// File not found
	ErrFileNotFound = Error{Code: 1511}
	// Unable to bind to network
	ErrBindFailed = Error{Code: 1512}
	// File could not be read
	ErrFileNotReadable = Error{Code: 1513}
	// File could not be written
	ErrFileNotWritable = Error{Code: 1514}
	// No cluster file found in current directory or default location
	ErrNoClusterFileFound = Error{Code: 1515}
	// File too large to be read
	ErrFileTooLarge = Error{Code: 1516}
	// Non sequential file operation not allowed
	ErrNonSequentialOp = Error{Code: 1517}
	// HTTP response was badly formed
	ErrHTTPBadResponse = Error{Code: 1518}
	// HTTP request not accepted
	ErrHTTPNotAccepted = Error{Code: 1519}
	// A data checksum failed
	ErrChecksumFailed = Error{Code: 1520}
	// A disk IO operation failed to complete in a timely manner
	ErrIOTimeout = Error{Code: 1521}
	// A structurally corrupt data file was detected
	ErrFileCorrupt = Error{Code: 1522}
	// HTTP response code not received or indicated failure
	ErrHTTPRequestFailed = Error{Code: 1523}
	// HTTP request failed due to bad credentials
	ErrHTTPAuthFailed = Error{Code: 1524}
	// HTTP response contained an unexpected X-Request-ID header
	ErrHTTPBadRequestID = Error{Code: 1525}
	// Invalid REST URI
	ErrRestInvalidURI = Error{Code: 1526}
	// Invalid RESTClient knob
	ErrRestInvalidRestClientKnob = Error{Code: 1527}
	// ConnectKey not found in connection pool
	ErrRestConnectpoolKeyNotFound = Error{Code: 1528}
	// Unable to lock the file
	ErrLockFileFailure = Error{Code: 1529}
	// Unsupported REST protocol
	ErrRestUnsupportedProtocol = Error{Code: 1530}
	// Malformed REST response
	ErrRestMalformedResponse = Error{Code: 1531}
	// Max BaseCipher length violation
	ErrRestMaxBaseCipherLen = Error{Code: 1532}
	// Requested resource was not found
	ErrResourceNotFound = Error{Code: 1533}
	// Invalid API call
	ErrClientInvalidOperation = Error{Code: 2000}
	// Commit with incomplete read
	ErrCommitReadIncomplete = Error{Code: 2002}
	// Invalid test specification
	ErrTestSpecificationInvalid = Error{Code: 2003}
	// Key outside legal range
	ErrKeyOutsideLegalRange = Error{Code: 2004}
	// Range begin key larger than end key
	ErrInvertedRange = Error{Code: 2005}
	// Option set with an invalid value
	ErrInvalidOptionValue = Error{Code: 2006}
	// Option not valid in this context
	ErrInvalidOption = Error{Code: 2007}
	// Action not possible before the network is configured
	ErrNetworkNotSetup = Error{Code: 2008}
	// Network can be configured only once
	ErrNetworkAlreadySetup = Error{Code: 2009}
	// Transaction already has a read version set
	ErrReadVersionAlreadySet = Error{Code: 2010}
	// Version not valid
	ErrVersionInvalid = Error{Code: 2011}
	// Range limits not valid
	ErrRangeLimitsInvalid = Error{Code: 2012}
	// Database name must be 'DB'
	ErrInvalidDatabaseName = Error{Code: 2013}
	// Attribute not found
	ErrAttributeNotFound = Error{Code: 2014}
	// Future not ready
	ErrFutureNotSet = Error{Code: 2015}
	// Future not an error
	ErrFutureNotError = Error{Code: 2016}
	// Operation issued while a commit was outstanding
	ErrUsedDuringCommit = Error{Code: 2017}
	// Unrecognized atomic mutation type
	ErrInvalidMutationType = Error{Code: 2018}
	// Attribute too large for type int
	ErrAttributeTooLarge = Error{Code: 2019}
	// Transaction does not have a valid commit version
	ErrTransactionInvalidVersion = Error{Code: 2020}
	// Transaction is read-only and therefore does not have a commit version
	ErrNoCommitVersion = Error{Code: 2021}
	// Environment variable network option could not be set
	ErrEnvironmentVariableNetworkOptionFailed = Error{Code: 2022}
	// Attempted to commit a transaction specified as read-only
	ErrTransactionReadOnly = Error{Code: 2023}
	// Invalid cache eviction policy, only random and lru are supported
	ErrInvalidCacheEvictionPolicy = Error{Code: 2024}
	// Network can only be started once
	ErrNetworkCannotBeRestarted = Error{Code: 2025}
	// Detected a deadlock in a callback called from the network thread
	ErrBlockedFromNetworkThread = Error{Code: 2026}
	// The index in K[] or V[] is not a valid number or out of range
	ErrMapperBadIndex = Error{Code: 2030}
	// A mapped key is not set in database
	ErrMapperNoSuchKey = Error{Code: 2031}
	// One of the mapped range queries is too large
	ErrQuickGetKeyValuesHasMore = Error{Code: 2033}
	// Found a mapped key that is not served in the same SS
	ErrQuickGetValueMiss = Error{Code: 2034}
	// Found a mapped range that is not served in the same SS
	ErrQuickGetKeyValuesMiss = Error{Code: 2035}
	// getMappedRange does not support continuation for now
	ErrGetMappedKeyValuesHasMore = Error{Code: 2038}
	// getMappedRange tries to read data that were previously written in the transaction
	ErrGetMappedRangeReadsYourWrites = Error{Code: 2039}
	// Checkpoint not found
	ErrCheckpointNotFound = Error{Code: 2040}
	// The key cannot be parsed as a tuple
	ErrKeyNotTuple = Error{Code: 2041}
	// The value cannot be parsed as a tuple
	ErrValueNotTuple = Error{Code: 2042}
	// The mapper cannot be parsed as a tuple
	ErrMapperNotTuple = Error{Code: 2043}
	// Invalid checkpoint format
	ErrInvalidCheckpointFormat = Error{Code: 2044}
	// Invalid quota value. Note that reserved_throughput cannot exceed total_throughput
	ErrInvalidThrottleQuotaValue = Error{Code: 2045}
	// Failed to create a checkpoint
	ErrFailedToCreateCheckpoint = Error{Code: 2046}
	// Failed to restore a checkpoint
	ErrFailedToRestoreCheckpoint = Error{Code: 2047}
	// Failed to dump shard metadata for a checkpoint to a sst file
	ErrFailedToCreateCheckpointShardMetadata = Error{Code: 2048}
	// Failed to parse address
	ErrAddressParseError = Error{Code: 2049}
	// Incompatible protocol version
	ErrIncompatibleProtocolVersion = Error{Code: 2100}
	// Transaction exceeds byte limit
	ErrTransactionTooLarge = Error{Code: 2101}
	// Key length exceeds limit
	ErrKeyTooLarge = Error{Code: 2102}
	// Value length exceeds limit
	ErrValueTooLarge = Error{Code: 2103}
	// Connection string invalid
	ErrConnectionStringInvalid = Error{Code: 2104}
	// Local address in use
	ErrAddressInUse = Error{Code: 2105}
	// Invalid local address
	ErrInvalidLocalAddress = Error{Code: 2106}
	// TLS error
	ErrTLSError = Error{Code: 2107}
	// Operation is not supported
	ErrUnsupportedOperation = Error{Code: 2108}
	// Too many tags set on transaction
	ErrTooManyTags = Error{Code: 2109}
	// Tag set on transaction is too long
	ErrTagTooLong = Error{Code: 2110}
	// Too many tag throttles have been created
	ErrTooManyTagThrottles = Error{Code: 2111}
	// Special key space range read crosses modules. Refer to the `special_key_space_relaxed' transaction option for more details.
	ErrSpecialKeysCrossModuleRead = Error{Code: 2112}
	// Special key space range read does not intersect a module. Refer to the `special_key_space_relaxed' transaction option for more details.
	ErrSpecialKeysNoModuleFound = Error{Code: 2113}
	// Special Key space is not allowed to write by default. Refer to the `special_key_space_enable_writes` transaction option for more details.
	ErrSpecialKeysWriteDisabled = Error{Code: 2114}
	// Special key space key or keyrange in set or clear does not intersect a module
	ErrSpecialKeysNoWriteModuleFound = Error{Code: 2115}
	// Special key space clear crosses modules
	ErrSpecialKeysCrossModuleClear = Error{Code: 2116}
	// Api call through special keys failed. For more information, call get on special key 0xff0xff/error_message to get a json string of the error message.
	ErrSpecialKeysAPIFailure = Error{Code: 2117}
	// Invalid client library metadata.
	ErrClientLibInvalidMetadata = Error{Code: 2118}
	// Client library with same identifier already exists on the cluster.
	ErrClientLibAlreadyExists = Error{Code: 2119}
	// Client library for the given identifier not found.
	ErrClientLibNotFound = Error{Code: 2120}
	// Client library exists, but is not available for download.
	ErrClientLibNotAvailable = Error{Code: 2121}
	// Invalid client library binary.
	ErrClientLibInvalidBinary = Error{Code: 2122}
	// No external client library provided.
	ErrNoExternalClientProvided = Error{Code: 2123}
	// All external clients have failed.
	ErrAllExternalClientsFailed = Error{Code: 2124}
	// None of the available clients match the protocol version of the cluster.
	ErrIncompatibleClient = Error{Code: 2125}
	// API version is not set
	ErrAPIVersionUnset = Error{Code: 2200}
	// API version may be set only once
	ErrAPIVersionAlreadySet = Error{Code: 2201}
	// API version not valid
	ErrAPIVersionInvalid = Error{Code: 2202}
	// API version not supported
	ErrAPIVersionNotSupported = Error{Code: 2203}
	// Failed to load a required FDB API function.
	ErrAPIFunctionMissing = Error{Code: 2204}
	// EXACT streaming mode requires limits, but none were given
	ErrExactModeWithoutLimits = Error{Code: 2210}
	// Unrecognized data type in packed tuple
	ErrInvalidTupleDataType = Error{Code: 2250}
	// Tuple does not have element at specified index
	ErrInvalidTupleIndex = Error{Code: 2251}
	// Cannot unpack key that is not in subspace
	ErrKeyNotInSubspace = Error{Code: 2252}
	// Cannot specify a prefix unless manual prefixes are enabled
	ErrManualPrefixesNotEnabled = Error{Code: 2253}
	// Cannot specify a prefix in a partition
	ErrPrefixInPartition = Error{Code: 2254}
	// Root directory cannot be opened
	ErrCannotOpenRootDirectory = Error{Code: 2255}
	// Directory already exists
	ErrDirectoryAlreadyExists = Error{Code: 2256}
	// Directory does not exist
	ErrDirectoryDoesNotExist = Error{Code: 2257}
	// Directory's parent does not exist
	ErrParentDirectoryDoesNotExist = Error{Code: 2258}
	// Directory has already been created with a different layer string
	ErrMismatchedLayer = Error{Code: 2259}
	// Invalid directory layer metadata
	ErrInvalidDirectoryLayerMetadata = Error{Code: 2260}
	// Directory cannot be moved between partitions
	ErrCannotMoveDirectoryBetweenPartitions = Error{Code: 2261}
	// Directory partition cannot be used as subspace
	ErrCannotUsePartitionAsSubspace = Error{Code: 2262}
	// Directory layer was created with an incompatible version
	ErrIncompatibleDirectoryVersion = Error{Code: 2263}
	// Database has keys stored at the prefix chosen by the automatic prefix allocator
	ErrDirectoryPrefixNotEmpty = Error{Code: 2264}
	// Directory layer already has a conflicting prefix
	ErrDirectoryPrefixInUse = Error{Code: 2265}
	// Target directory is invalid
	ErrInvalidDestinationDirectory = Error{Code: 2266}
	// Root directory cannot be modified
	ErrCannotModifyRootDirectory = Error{Code: 2267}
	// UUID is not sixteen bytes
	ErrInvalidUUIDSize = Error{Code: 2268}
	// Versionstamp is not exactly twelve bytes
	ErrInvalidVersionstampSize = Error{Code: 2269}
	// Backup error
	ErrBackupError = Error{Code: 2300}
	// Restore error
	ErrRestoreError = Error{Code: 2301}
	// Backup duplicate request
	ErrBackupDuplicate = Error{Code: 2311}
	// Backup unneeded request
	ErrBackupUnneeded = Error{Code: 2312}
	// Backup file block size too small
	ErrBackupBadBlockSize = Error{Code: 2313}
	// Backup Container URL invalid
	ErrBackupInvalidURL = Error{Code: 2314}
	// Backup Container info invalid
	ErrBackupInvalidInfo = Error{Code: 2315}
	// Cannot expire requested data from backup without violating minimum restorability
	ErrBackupCannotExpire = Error{Code: 2316}
	// Cannot find authentication details (such as a password or secret key) for the specified Backup Container URL
	ErrBackupAuthMissing = Error{Code: 2317}
	// Cannot read or parse one or more sources of authentication information for Backup Container URLs
	ErrBackupAuthUnreadable = Error{Code: 2318}
	// Backup does not exist
	ErrBackupDoesNotExist = Error{Code: 2319}
	// Backup before 6.3 cannot be filtered with key ranges
	ErrBackupNotFilterableWithKeyRanges = Error{Code: 2320}
	// Backup key ranges doesn't overlap with key ranges filter
	ErrBackupNotOverlappedWithKeysFilter = Error{Code: 2321}
	// bucket is not in the URL for backup
	ErrBucketNotInURL = Error{Code: 2322}
	// Invalid restore version
	ErrRestoreInvalidVersion = Error{Code: 2361}
	// Corrupted backup data
	ErrRestoreCorruptedData = Error{Code: 2362}
	// Missing backup data
	ErrRestoreMissingData = Error{Code: 2363}
	// Restore duplicate request
	ErrRestoreDuplicateTag = Error{Code: 2364}
	// Restore tag does not exist
	ErrRestoreUnknownTag = Error{Code: 2365}
	// Unknown backup/restore file type
	ErrRestoreUnknownFileType = Error{Code: 2366}
	// Unsupported backup file version
	ErrRestoreUnsupportedFileVersion = Error{Code: 2367}
	// Unexpected number of bytes read
	ErrRestoreBadRead = Error{Code: 2368}
	// Backup file has unexpected padding bytes
	ErrRestoreCorruptedDataPadding = Error{Code: 2369}
	// Attempted to restore into a non-empty destination database
	ErrRestoreDestinationNotEmpty = Error{Code: 2370}
	// Attempted to restore using a UID that had been used for an aborted restore
	ErrRestoreDuplicateUID = Error{Code: 2371}
	// Invalid task version
	ErrTaskInvalidVersion = Error{Code: 2381}
	// Task execution stopped due to timeout, abort, or completion by another worker
	ErrTaskInterrupted = Error{Code: 2382}
	// The provided encryption key file has invalid contents
	ErrInvalidEncryptionKeyFile = Error{Code: 2383}
	// Missing mutation logs
	ErrBlobRestoreMissingLogs = Error{Code: 2384}
	// Corrupted mutation logs
	ErrBlobRestoreCorruptedLogs = Error{Code: 2385}
	// Invalid manifest URL
	ErrBlobRestoreInvalidManifestURL = Error{Code: 2386}
	// Corrupted manifest
	ErrBlobRestoreCorruptedManifest = Error{Code: 2387}
	// Missing manifest
	ErrBlobRestoreMissingManifest = Error{Code: 2388}
	// Blob migrator is replaced
	ErrBlobMigratorReplaced = Error{Code: 2389}
	// BulkDump dataset incomplete. Use --rangefile flag
	ErrRestoreBulkloadDatasetIncomplete = Error{Code: 2390}
	// BulkLoad operation failed
	ErrRestoreBulkloadFailed = Error{Code: 2391}
	// BulkDump operation timed out
	ErrBackupBulkdumpTimeout = Error{Code: 2392}
	// BulkDump operation failed
	ErrBackupBulkdumpFailed = Error{Code: 2393}
	// Expected key is missing
	ErrKeyNotFound = Error{Code: 2400}
	// JSON string was malformed
	ErrJSONMalformed = Error{Code: 2401}
	// JSON string did not terminate where expected
	ErrJSONEofExpected = Error{Code: 2402}
	// Failed to disable tlog pops
	ErrSnapDisableTLogPopFailed = Error{Code: 2500}
	// Failed to snapshot storage nodes
	ErrSnapStorageFailed = Error{Code: 2501}
	// Failed to snapshot TLog nodes
	ErrSnapTLogFailed = Error{Code: 2502}
	// Failed to snapshot coordinator nodes
	ErrSnapCoordFailed = Error{Code: 2503}
	// Failed to enable tlog pops
	ErrSnapEnableTLogPopFailed = Error{Code: 2504}
	// Snapshot create binary path not whitelisted
	ErrSnapPathNotWhitelisted = Error{Code: 2505}
	// Unsupported when the cluster is not fully recovered
	ErrSnapNotFullyRecoveredUnsupported = Error{Code: 2506}
	// Unsupported when log anti quorum is configured
	ErrSnapLogAntiQuorumUnsupported = Error{Code: 2507}
	// Cluster recovery during snapshot operation not supported
	ErrSnapWithRecoveryUnsupported = Error{Code: 2508}
	// The given uid string is not a 32-length hex string
	ErrSnapInvalidUIDString = Error{Code: 2509}
	// Encryption operation error
	ErrEncryptOpsError = Error{Code: 2700}
	// Encryption header metadata mismatch
	ErrEncryptHeaderMetadataMismatch = Error{Code: 2701}
	// Expected encryption key is missing
	ErrEncryptKeyNotFound = Error{Code: 2702}
	// Expected encryption key TTL has expired
	ErrEncryptKeyTTLExpired = Error{Code: 2703}
	// Encryption header authentication token mismatch
	ErrEncryptHeaderAuthtokenMismatch = Error{Code: 2704}
	// Attempt to update encryption cipher key
	ErrEncryptUpdateCipher = Error{Code: 2705}
	// Invalid encryption cipher details
	ErrEncryptInvalidID = Error{Code: 2706}
	// Encryption keys fetch from external KMS failed
	ErrEncryptKeysFetchFailed = Error{Code: 2707}
	// Invalid encryption/kms configuration: discovery-url, validation-token, endpoint etc.
	ErrEncryptInvalidKMSConfig = Error{Code: 2708}
	// Encryption not supported
	ErrEncryptUnsupported = Error{Code: 2709}
	// Encryption mode mismatch with configuration
	ErrEncryptModeMismatch = Error{Code: 2710}
	// Encryption key-check-value mismatch
	ErrEncryptKeyCheckValueMismatch = Error{Code: 2711}
	// Max BaseCipher buffer length violation
	ErrEncryptMaxBaseCipherLen = Error{Code: 2712}
	// An unknown error occurred
	ErrUnknownError = Error{Code: 4000}
	// An internal error occurred
	ErrInternalError = Error{Code: 4100}
	// Not implemented yet
	ErrNotImplemented = Error{Code: 4200}
	// Client tried to access unauthorized data
	ErrPermissionDenied = Error{Code: 6000}
	// A untrusted client tried to send a message to a private endpoint
	ErrUnauthorizedAttempt = Error{Code: 6001}
	// Digital signature operation error
	ErrDigitalSignatureOpsError = Error{Code: 6002}
	// Failed to verify authorization token
	ErrAuthorizationTokenVerifyFailed = Error{Code: 6003}
	// Failed to decode public/private key
	ErrPkeyDecodeError = Error{Code: 6004}
	// Failed to encode public/private key
	ErrPkeyEncodeError = Error{Code: 6005}
	// gRPC Error
	ErrGRPCError = Error{Code: 7000}
)
