[package]
name = "foundationdb-profiling"
version = "0.1.0"
authors = [
    "Pierre Zemb <contact@pierrezemb.fr>"
]
edition = "2024"
rust-version = "1.85.1"

description = """
Read and decode FoundationDB client transaction profiling data
"""

documentation = "https://docs.rs/foundationdb-profiling"
repository = "https://github.com/foundationdb-rs/foundationdb-rs"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["foundationdb", "profiling"]
categories = ["database", "development-tools::profiling"]

[badges]
codecov = { repository = "foundationdb-rs/foundationdb-rs", branch = "main", service = "github" }

[dependencies]
futures-core = "0.3.32"
thiserror = "2.0.18"
tracing = "0.1.44"

[dev-dependencies]
foundationdb = { version = "0.11.0", path = "../foundationdb", default-features = false, features = ["fdb-7_4", "embedded-fdb-include"] }
futures-util = "0.3.32"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "time"] }
