// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fdbrpc.proto

#include "fdbrpc/fdbrpc.pb.h"
#include "fdbrpc/fdbrpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace fdbrpc {

static const char* FDBRpcService_method_names[] = {
  "/fdbrpc.FDBRpcService/Echo",
};

std::unique_ptr< FDBRpcService::Stub> FDBRpcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FDBRpcService::Stub> stub(new FDBRpcService::Stub(channel, options));
  return stub;
}

FDBRpcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Echo_(FDBRpcService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FDBRpcService::Stub::Echo(::grpc::ClientContext* context, const ::fdbrpc::EchoRequest& request, ::fdbrpc::EchoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fdbrpc::EchoRequest, ::fdbrpc::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Echo_, context, request, response);
}

void FDBRpcService::Stub::async::Echo(::grpc::ClientContext* context, const ::fdbrpc::EchoRequest* request, ::fdbrpc::EchoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fdbrpc::EchoRequest, ::fdbrpc::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, std::move(f));
}

void FDBRpcService::Stub::async::Echo(::grpc::ClientContext* context, const ::fdbrpc::EchoRequest* request, ::fdbrpc::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fdbrpc::EchoResponse>* FDBRpcService::Stub::PrepareAsyncEchoRaw(::grpc::ClientContext* context, const ::fdbrpc::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fdbrpc::EchoResponse, ::fdbrpc::EchoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fdbrpc::EchoResponse>* FDBRpcService::Stub::AsyncEchoRaw(::grpc::ClientContext* context, const ::fdbrpc::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEchoRaw(context, request, cq);
  result->StartCall();
  return result;
}

FDBRpcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FDBRpcService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FDBRpcService::Service, ::fdbrpc::EchoRequest, ::fdbrpc::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FDBRpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fdbrpc::EchoRequest* req,
             ::fdbrpc::EchoResponse* resp) {
               return service->Echo(ctx, req, resp);
             }, this)));
}

FDBRpcService::Service::~Service() {
}

::grpc::Status FDBRpcService::Service::Echo(::grpc::ServerContext* context, const ::fdbrpc::EchoRequest* request, ::fdbrpc::EchoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fdbrpc

