string(REPLACE "/" "\\" fdbserver "${fdbserver}")
string(REPLACE "/" "\\" fdbcli "${fdbcli}")
string(REPLACE "/" "\\" fdbbackup "${fdbbackup}")
string(REPLACE "/" "\\" fdbmonitor "${fdbmonitor}")
string(REPLACE "/" "\\" fdbc "${fdbc}")
string(REPLACE "dll" "lib" fdbc_lib "${fdbc}")
string(REPLACE "/" "\\" SOURCE_ROOT "${SOURCE_ROOT}\\")
string(REPLACE "/" "\\" BUILD_ROOT "${BUILD_ROOT}\\")
string(REPLACE "/" "\\" CURRENT_SOURCE_DIR "${CURRENT_SOURCE_DIR}\\")
message(STATUS "Configure WIX (from ${IN} to ${OUT}) with ${fdbserver} ${fdbcli} ${fdbbackup} ${fdbmonitor} ${fdbc}")
configure_file(${IN} ${OUT} @ONLY NEWLINE_STYLE DOS)
