[[test]]
testTitle = 'TracingDemoWorkload'

  [[test.workload]]
    testName = 'External'
    useCAPI = true
    libraryName = 'tracing_demo'
    workloadName = 'TracingDemoWorkload'
    libraryPath = './target/release/examples'
