# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import control_service_pb2 as control__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in control_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """-- RPCs ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoordinators = channel.unary_unary(
                '/fdbctl.ControlService/GetCoordinators',
                request_serializer=control__service__pb2.GetCoordinatorsRequest.SerializeToString,
                response_deserializer=control__service__pb2.GetCoordinatorsReply.FromString,
                _registered_method=True)
        self.ChangeCoordinators = channel.unary_unary(
                '/fdbctl.ControlService/ChangeCoordinators',
                request_serializer=control__service__pb2.ChangeCoordinatorsRequest.SerializeToString,
                response_deserializer=control__service__pb2.ChangeCoordinatorsReply.FromString,
                _registered_method=True)
        self.ConfigureAutoSuggest = channel.unary_unary(
                '/fdbctl.ControlService/ConfigureAutoSuggest',
                request_serializer=control__service__pb2.ConfigureAutoSuggestRequest.SerializeToString,
                response_deserializer=control__service__pb2.ConfigureAutoSuggestReply.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/fdbctl.ControlService/Configure',
                request_serializer=control__service__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=control__service__pb2.ConfigureReply.FromString,
                _registered_method=True)
        self.GetReadVersion = channel.unary_unary(
                '/fdbctl.ControlService/GetReadVersion',
                request_serializer=control__service__pb2.GetReadVersionRequest.SerializeToString,
                response_deserializer=control__service__pb2.GetReadVersionReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/fdbctl.ControlService/GetStatus',
                request_serializer=control__service__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=control__service__pb2.GetStatusReply.FromString,
                _registered_method=True)
        self.GetWorkers = channel.unary_unary(
                '/fdbctl.ControlService/GetWorkers',
                request_serializer=control__service__pb2.GetWorkersRequest.SerializeToString,
                response_deserializer=control__service__pb2.GetWorkersReply.FromString,
                _registered_method=True)
        self.Include = channel.unary_unary(
                '/fdbctl.ControlService/Include',
                request_serializer=control__service__pb2.IncludeRequest.SerializeToString,
                response_deserializer=control__service__pb2.IncludeReply.FromString,
                _registered_method=True)
        self.Exclude = channel.unary_unary(
                '/fdbctl.ControlService/Exclude',
                request_serializer=control__service__pb2.ExcludeRequest.SerializeToString,
                response_deserializer=control__service__pb2.ExcludeReply.FromString,
                _registered_method=True)
        self.ExcludeStatus = channel.unary_unary(
                '/fdbctl.ControlService/ExcludeStatus',
                request_serializer=control__service__pb2.ExcludeStatusRequest.SerializeToString,
                response_deserializer=control__service__pb2.ExcludeStatusReply.FromString,
                _registered_method=True)
        self.Kill = channel.unary_unary(
                '/fdbctl.ControlService/Kill',
                request_serializer=control__service__pb2.KillRequest.SerializeToString,
                response_deserializer=control__service__pb2.KillReply.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """-- RPCs ----

    """

    def GetCoordinators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeCoordinators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureAutoSuggest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReadVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Include(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exclude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExcludeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoordinators': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoordinators,
                    request_deserializer=control__service__pb2.GetCoordinatorsRequest.FromString,
                    response_serializer=control__service__pb2.GetCoordinatorsReply.SerializeToString,
            ),
            'ChangeCoordinators': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeCoordinators,
                    request_deserializer=control__service__pb2.ChangeCoordinatorsRequest.FromString,
                    response_serializer=control__service__pb2.ChangeCoordinatorsReply.SerializeToString,
            ),
            'ConfigureAutoSuggest': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureAutoSuggest,
                    request_deserializer=control__service__pb2.ConfigureAutoSuggestRequest.FromString,
                    response_serializer=control__service__pb2.ConfigureAutoSuggestReply.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=control__service__pb2.ConfigureRequest.FromString,
                    response_serializer=control__service__pb2.ConfigureReply.SerializeToString,
            ),
            'GetReadVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReadVersion,
                    request_deserializer=control__service__pb2.GetReadVersionRequest.FromString,
                    response_serializer=control__service__pb2.GetReadVersionReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=control__service__pb2.GetStatusRequest.FromString,
                    response_serializer=control__service__pb2.GetStatusReply.SerializeToString,
            ),
            'GetWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkers,
                    request_deserializer=control__service__pb2.GetWorkersRequest.FromString,
                    response_serializer=control__service__pb2.GetWorkersReply.SerializeToString,
            ),
            'Include': grpc.unary_unary_rpc_method_handler(
                    servicer.Include,
                    request_deserializer=control__service__pb2.IncludeRequest.FromString,
                    response_serializer=control__service__pb2.IncludeReply.SerializeToString,
            ),
            'Exclude': grpc.unary_unary_rpc_method_handler(
                    servicer.Exclude,
                    request_deserializer=control__service__pb2.ExcludeRequest.FromString,
                    response_serializer=control__service__pb2.ExcludeReply.SerializeToString,
            ),
            'ExcludeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ExcludeStatus,
                    request_deserializer=control__service__pb2.ExcludeStatusRequest.FromString,
                    response_serializer=control__service__pb2.ExcludeStatusReply.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=control__service__pb2.KillRequest.FromString,
                    response_serializer=control__service__pb2.KillReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fdbctl.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fdbctl.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """-- RPCs ----

    """

    @staticmethod
    def GetCoordinators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/GetCoordinators',
            control__service__pb2.GetCoordinatorsRequest.SerializeToString,
            control__service__pb2.GetCoordinatorsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeCoordinators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/ChangeCoordinators',
            control__service__pb2.ChangeCoordinatorsRequest.SerializeToString,
            control__service__pb2.ChangeCoordinatorsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureAutoSuggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/ConfigureAutoSuggest',
            control__service__pb2.ConfigureAutoSuggestRequest.SerializeToString,
            control__service__pb2.ConfigureAutoSuggestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/Configure',
            control__service__pb2.ConfigureRequest.SerializeToString,
            control__service__pb2.ConfigureReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReadVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/GetReadVersion',
            control__service__pb2.GetReadVersionRequest.SerializeToString,
            control__service__pb2.GetReadVersionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/GetStatus',
            control__service__pb2.GetStatusRequest.SerializeToString,
            control__service__pb2.GetStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/GetWorkers',
            control__service__pb2.GetWorkersRequest.SerializeToString,
            control__service__pb2.GetWorkersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Include(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/Include',
            control__service__pb2.IncludeRequest.SerializeToString,
            control__service__pb2.IncludeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exclude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/Exclude',
            control__service__pb2.ExcludeRequest.SerializeToString,
            control__service__pb2.ExcludeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExcludeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/ExcludeStatus',
            control__service__pb2.ExcludeStatusRequest.SerializeToString,
            control__service__pb2.ExcludeStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fdbctl.ControlService/Kill',
            control__service__pb2.KillRequest.SerializeToString,
            control__service__pb2.KillReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
