#! /usr/bin/env ruby

require 'erb'

source_names = Dir['*.actor.cpp']

def get_executable_name(source_name)
  'async_' + File.basename(File.basename(source_name, '.cpp'), '.actor')
end

template = ERB.new(%{# Generated by generate_cmakelists.rb, do not modify
<% source_names.each do |source_name| %>
<% target_name = get_executable_name(source_name) %>
add_flow_target(EXECUTABLE NAME <%= target_name  %> SRCS "<%= source_name %>")
target_link_libraries(<%= target_name %> PUBLIC fdbclient)
set_target_properties(<%= target_name %> PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin/extra_tutorials/)
<% end %>
})

File.new('CMakeLists.txt', 'w').write(template.result())
