//go:build ignore

/*
 * main.go
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2013-2026 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// gen_errors reads flow/include/flow/error_definitions.h and generates a Go
// source file containing integer constants for every FDB error code.
//
// Usage:
//
//	go run internal/gen_errors/main.go <input.h> <output.go>
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
	"text/template"
	"unicode"
)

var errorRe = regexp.MustCompile(`^\s*ERROR\(\s*(\w+)\s*,\s*(\d+)\s*,\s*"([^"]+)"\s*\)`)

// initialism maps lower-case words that should be fully uppercased in Go names.
var initialism = map[string]string{
	"api":  "API",
	"db":   "DB",
	"dns":  "DNS",
	"grpc": "GRPC",
	"grv":  "GRV",
	"http": "HTTP",
	"id":   "ID",
	"ids":  "IDs",
	"io":   "IO",
	"ip":   "IP",
	"json": "JSON",
	"kms":  "KMS",
	"kv":   "KV",
	"ssl":  "SSL",
	"tlog": "TLog",
	"tls":  "TLS",
	"ttl":  "TTL",
	"uid":  "UID",
	"uri":  "URI",
	"url":  "URL",
	"uuid": "UUID",
}

type errorDef struct {
	Name        string // exported Go constant name, e.g. ErrCodeTransactionTooOld
	Code        string // numeric string, e.g. "1007"
	Description string // human-readable description from the macro
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		if upper, ok := initialism[strings.ToLower(p)]; ok {
			b.WriteString(upper)
			continue
		}
		runes := []rune(p)
		b.WriteRune(unicode.ToUpper(runes[0]))
		b.WriteString(string(runes[1:]))
	}
	return b.String()
}

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintln(os.Stderr, "usage: gen_errors <input.h> <output.go>")
		os.Exit(1)
	}

	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "open %s: %v\n", os.Args[1], err)
		os.Exit(1)
	}
	defer f.Close()

	var defs []errorDef
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		m := errorRe.FindStringSubmatch(scanner.Text())
		if m == nil {
			continue
		}
		defs = append(defs, errorDef{
			Name:        "Err" + toPascalCase(m[1]),
			Code:        m[2],
			Description: m[3],
		})
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", err)
		os.Exit(1)
	}

	out, err := os.Create(os.Args[2])
	if err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", os.Args[2], err)
		os.Exit(1)
	}
	defer out.Close()

	if err := tmpl.Execute(out, defs); err != nil {
		fmt.Fprintf(os.Stderr, "template: %v\n", err)
		os.Exit(1)
	}
}

var tmpl = template.Must(template.New("").Parse(`// Code generated by gen_errors. DO NOT EDIT.

/*
 * error_codes_generated.go
 *
 * This source file is part of the FoundationDB open source project
 *
 * Copyright 2013-2026 Apple Inc. and the FoundationDB project authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fdb

// Error sentinel variables derived from flow/include/flow/error_definitions.h.
// Use with errors.Is to match a specific FoundationDB error code:
//
//	errors.Is(err, fdb.ErrTransactionTooOld)
var (
{{- range .}}
	// {{.Description}}
	{{.Name}} = Error{Code: {{.Code}}}
{{- end}}
)
`))
