# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network_test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='network_test.proto',
  package='foundationdb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12network_test.proto\x12\x0c\x66oundationdb\"4\n\x12NetworkTestRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x11\n\treplySize\x18\x02 \x01(\r\"!\n\x10NetworkTestReply\x12\r\n\x05value\x18\x01 \x01(\x0c\x32]\n\x0bNetworkTest\x12N\n\x08GetValue\x12 .foundationdb.NetworkTestRequest\x1a\x1e.foundationdb.NetworkTestReply\"\x00\x62\x06proto3')
)




_NETWORKTESTREQUEST = _descriptor.Descriptor(
  name='NetworkTestRequest',
  full_name='foundationdb.NetworkTestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='foundationdb.NetworkTestRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replySize', full_name='foundationdb.NetworkTestRequest.replySize', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=88,
)


_NETWORKTESTREPLY = _descriptor.Descriptor(
  name='NetworkTestReply',
  full_name='foundationdb.NetworkTestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='foundationdb.NetworkTestReply.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['NetworkTestRequest'] = _NETWORKTESTREQUEST
DESCRIPTOR.message_types_by_name['NetworkTestReply'] = _NETWORKTESTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkTestRequest = _reflection.GeneratedProtocolMessageType('NetworkTestRequest', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKTESTREQUEST,
  '__module__' : 'network_test_pb2'
  # @@protoc_insertion_point(class_scope:foundationdb.NetworkTestRequest)
  })
_sym_db.RegisterMessage(NetworkTestRequest)

NetworkTestReply = _reflection.GeneratedProtocolMessageType('NetworkTestReply', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKTESTREPLY,
  '__module__' : 'network_test_pb2'
  # @@protoc_insertion_point(class_scope:foundationdb.NetworkTestReply)
  })
_sym_db.RegisterMessage(NetworkTestReply)



_NETWORKTEST = _descriptor.ServiceDescriptor(
  name='NetworkTest',
  full_name='foundationdb.NetworkTest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=125,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetValue',
    full_name='foundationdb.NetworkTest.GetValue',
    index=0,
    containing_service=None,
    input_type=_NETWORKTESTREQUEST,
    output_type=_NETWORKTESTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORKTEST)

DESCRIPTOR.services_by_name['NetworkTest'] = _NETWORKTEST

# @@protoc_insertion_point(module_scope)
