// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: network_test.proto

#include "network_test.pb.h"
#include "network_test.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace foundationdb {

static const char* NetworkTest_method_names[] = {
  "/foundationdb.NetworkTest/GetValue",
};

std::unique_ptr< NetworkTest::Stub> NetworkTest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NetworkTest::Stub> stub(new NetworkTest::Stub(channel));
  return stub;
}

NetworkTest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetValue_(NetworkTest_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NetworkTest::Stub::GetValue(::grpc::ClientContext* context, const ::foundationdb::NetworkTestRequest& request, ::foundationdb::NetworkTestReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetValue_, context, request, response);
}

void NetworkTest::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::foundationdb::NetworkTestRequest* request, ::foundationdb::NetworkTestReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, std::move(f));
}

void NetworkTest::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::foundationdb::NetworkTestReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, std::move(f));
}

void NetworkTest::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::foundationdb::NetworkTestRequest* request, ::foundationdb::NetworkTestReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, reactor);
}

void NetworkTest::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::foundationdb::NetworkTestReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::foundationdb::NetworkTestReply>* NetworkTest::Stub::AsyncGetValueRaw(::grpc::ClientContext* context, const ::foundationdb::NetworkTestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::foundationdb::NetworkTestReply>::Create(channel_.get(), cq, rpcmethod_GetValue_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::foundationdb::NetworkTestReply>* NetworkTest::Stub::PrepareAsyncGetValueRaw(::grpc::ClientContext* context, const ::foundationdb::NetworkTestRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::foundationdb::NetworkTestReply>::Create(channel_.get(), cq, rpcmethod_GetValue_, context, request, false);
}

NetworkTest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NetworkTest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NetworkTest::Service, ::foundationdb::NetworkTestRequest, ::foundationdb::NetworkTestReply>(
          std::mem_fn(&NetworkTest::Service::GetValue), this)));
}

NetworkTest::Service::~Service() {
}

::grpc::Status NetworkTest::Service::GetValue(::grpc::ServerContext* context, const ::foundationdb::NetworkTestRequest* request, ::foundationdb::NetworkTestReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace foundationdb

