# RPM specifics
if(CPACK_GENERATOR MATCHES "RPM")
  set(CPACK_COMPONENTS_ALL clients-el6 clients-el7 server-el6 server-el7)
elseif(CPACK_GENERATOR MATCHES "DEB")
  set(CPACK_COMPONENTS_ALL clients-deb server-deb)
elseif(CPACK_GENERATOR MATCHES "PackageMaker")
  set(CPACK_COMPONENTS_ALL clients-pm server-pm)
  set(CPACK_STRIP_FILES TRUE)
  set(CPACK_PREFLIGHT_SERVER_SCRIPT ${CMAKE_SOURCE_DIR}/packaging/osx/scripts-server/preinstall)
  set(CPACK_POSTFLIGHT_SERVER_SCRIPT ${CMAKE_SOURCE_DIR}/packaging/osx/scripts-server/postinstall)
  set(CPACK_POSTFLIGHT_CLIENTS_SCRIPT ${CMAKE_SOURCE_DIR}/packaging/osx/scripts-server/preinstall)
elseif(CPACK_GENERATOR MATCHES "TGZ")
  set(CPACK_STRIP_FILES TRUE)
  set(CPACK_COMPONENTS_ALL clients-tgz server-tgz)
else()
  message(FATAL_ERROR "Unsupported package format ${CPACK_GENERATOR}")
endif()
