// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv_service.proto
#ifndef GRPC_kv_5fservice_2eproto__INCLUDED
#define GRPC_kv_5fservice_2eproto__INCLUDED

#include "kv_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace foundationdb {

class FdbKvClient final {
 public:
  static constexpr char const* service_full_name() {
    return "foundationdb.FdbKvClient";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::foundationdb::GetValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::foundationdb::GetValueReply>> AsyncGetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::foundationdb::GetValueReply>>(AsyncGetValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::foundationdb::GetValueReply>> PrepareAsyncGetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::foundationdb::GetValueReply>>(PrepareAsyncGetValueRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest* request, ::foundationdb::GetValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::foundationdb::GetValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest* request, ::foundationdb::GetValueReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::foundationdb::GetValueReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::foundationdb::GetValueReply>* AsyncGetValueRaw(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::foundationdb::GetValueReply>* PrepareAsyncGetValueRaw(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::foundationdb::GetValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::foundationdb::GetValueReply>> AsyncGetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::foundationdb::GetValueReply>>(AsyncGetValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::foundationdb::GetValueReply>> PrepareAsyncGetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::foundationdb::GetValueReply>>(PrepareAsyncGetValueRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest* request, ::foundationdb::GetValueReply* response, std::function<void(::grpc::Status)>) override;
      void GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::foundationdb::GetValueReply* response, std::function<void(::grpc::Status)>) override;
      void GetValue(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest* request, ::foundationdb::GetValueReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::foundationdb::GetValueReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::foundationdb::GetValueReply>* AsyncGetValueRaw(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::foundationdb::GetValueReply>* PrepareAsyncGetValueRaw(::grpc::ClientContext* context, const ::foundationdb::GetValueRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetValue_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetValue(::grpc::ServerContext* context, const ::foundationdb::GetValueRequest* request, ::foundationdb::GetValueReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetValue() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetValue(::grpc::ServerContext* context, ::foundationdb::GetValueRequest* request, ::grpc::ServerAsyncResponseWriter< ::foundationdb::GetValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetValue<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetValue() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::foundationdb::GetValueRequest, ::foundationdb::GetValueReply>(
          [this](::grpc::ServerContext* context,
                 const ::foundationdb::GetValueRequest* request,
                 ::foundationdb::GetValueReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GetValue(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_GetValue(
        ::grpc::experimental::MessageAllocator< ::foundationdb::GetValueRequest, ::foundationdb::GetValueReply>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::foundationdb::GetValueRequest, ::foundationdb::GetValueReply>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GetValue<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetValue() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetValue() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetValue(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetValue() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetValue(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GetValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetValue(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetValue() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::foundationdb::GetValueRequest, ::foundationdb::GetValueReply>(std::bind(&WithStreamedUnaryMethod_GetValue<BaseClass>::StreamedGetValue, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetValue(::grpc::ServerContext* /*context*/, const ::foundationdb::GetValueRequest* /*request*/, ::foundationdb::GetValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetValue(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::foundationdb::GetValueRequest,::foundationdb::GetValueReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetValue<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetValue<Service > StreamedService;
};

}  // namespace foundationdb


#endif  // GRPC_kv_5fservice_2eproto__INCLUDED
