name: clang-format

on:
  pull_request:
    branches:
      - main
      - release-7.4

permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          # by default PR virtual "merge" commit is checked-out
          ref: ${{ github.event.pull_request.head.sha }}

      - name: tool versions
        run: |
          clang-format --version

      - name: clang-format
        run: |
          find . -type f '(' -name \*.c -or -name \*.cpp -or -name \*.h -or -name \*.hpp ')' \
                 -not -name sqlite3.amalgamation.c \
                 -exec clang-format -i '{}' ';'

          git diff --exit-code
