taskset -c 0-2 /root/build_output/bin/fdbserver \
	-r unittests \
	-f :/network/p2ptest \
	--test_remoteAddresses=127.0.0.1:4500:tls \
	--test_targetDuration=10 \
	--test_connectionsOut=10 \
	--knob_disable_mainthread_tls_handshake=true \
	--knob_tls_handshake_flowlock_priority=8900 \
	--tls_ca_file keys/ca_file.crt \
	--tls_certificate_file keys/certificate_file.crt  \
	--tls_key_file keys/key_file.key  \
	--tls_verify_peers "Root.CN=dummy-ca"